import { app } from 'electron'
import { existsSync, mkdirSync } from 'node:fs'
import path from 'node:path'

/**
 * Dev mode loads the Vite server. `CLIPFORGE_DEV=0` runs an unpackaged build
 * against the compiled renderer, which is how the production path is smoke-tested.
 */
export const isDev = (): boolean =>
  process.env.CLIPFORGE_DEV === '1' || (!app.isPackaged && process.env.CLIPFORGE_DEV !== '0')

/**
 * Bundled media binaries live in `resources/bin` during development and in the
 * packaged app's resources directory after installation.
 */
export function binDir(): string {
  const candidates: string[] = []
  if (app.isPackaged) candidates.push(path.join(process.resourcesPath, 'bin'))
  candidates.push(path.join(app.getAppPath(), 'resources', 'bin'))
  candidates.push(path.join(process.cwd(), 'resources', 'bin'))
  return candidates.find((dir) => existsSync(dir)) ?? candidates[0]!
}

/**
 * Window/taskbar icon. Generated by `npm run make:icon`; in a packaged app it
 * ships as an extra resource next to `bin/`.
 */
export function iconPath(): string | undefined {
  const candidates = app.isPackaged
    ? [path.join(process.resourcesPath, 'icon.png')]
    : [path.join(app.getAppPath(), 'build', 'icon.png'), path.join(process.cwd(), 'build', 'icon.png')]
  return candidates.find((file) => existsSync(file))
}

export function ensureDir(dir: string): string {
  mkdirSync(dir, { recursive: true })
  return dir
}

export function defaultOutputDir(): string {
  return path.join(app.getPath('pictures'), 'ClipForge')
}

export function resolveOutputDir(configured: string): string {
  return ensureDir(configured && configured.trim().length > 0 ? configured : defaultOutputDir())
}

/**
 * Stable scratch area for tool downloads. Sharing one path across attempts is what
 * lets an interrupted 111 MB FFmpeg download resume instead of starting over.
 */
export function installCacheDir(): string {
  return ensureDir(path.join(app.getPath('temp'), 'clipforge-install'))
}

/** Unique scratch directory; every job cleans up only inside its own folder. */
export function workDir(prefix: string): string {
  const name = `clipforge-${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`
  return ensureDir(path.join(app.getPath('temp'), name))
}

export function settingsPath(): string {
  return path.join(app.getPath('userData'), 'settings.json')
}

/** Remembers the clip being trimmed so a restart can offer to continue. */
export function sessionPath(): string {
  return path.join(app.getPath('userData'), 'session.json')
}

export function rendererEntry(): string {
  return path.join(app.getAppPath(), 'dist', 'renderer', 'index.html')
}

export function preloadEntry(): string {
  return path.join(__dirname, '..', 'preload', 'index.js')
}
